/**
 * pages/movie_performance.js
 * Enhanced version with AI-ready chart metadata support.
 */

import {
  getGenre,
  getRating,
  getGenreRating,
  getFilms,
  getCustomers,
  postRental
} from "../api.js";

import { ChartRegistry } from "../chart_registry.js";

const PALETTE = [
  "#E6A341","#B14A36","#8C0902","#FECE79","#210100",
  "#D4845A","#A0522D","#C0392B","#E67E22","#6C3483",
  "#1F618D","#117A65","#884EA0","#2E86C1","#1E8449","#B7950B"
];

const RATING_COLORS = {
  G:"#059669",
  PG:"#2563eb",
  "PG-13":"#E6A341",
  R:"#B14A36",
  "NC-17":"#8C0902"
};

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

function mkChart(
  id,
  type,
  labels,
  datasets,
  opts = {},
  meta = {}
) {
  const ctx = document.getElementById(id)?.getContext("2d");
  if (!ctx) return null;

  const chart = new Chart(ctx, {
    type,
    data: {
      labels,
      datasets
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,

      plugins: {
        legend: {
          display: opts.legend ?? false
        }
      },

      scales: opts.scales,
      ...opts.extra
    }
  });

  ChartRegistry.register(id, chart, {
    page: "movie",
    title: meta.title || id,
    category: meta.category || "general",
    description: meta.description || "",
    xLabel: meta.xLabel || "",
    yLabel: meta.yLabel || "",
    keywords: meta.keywords || [],
    ...meta
  });

  return chart;
}

function buildKPIs(container, items) {
  container.innerHTML = items.map(({ label, value, accent }) => `
    <div class="kpi-card" style="--accent:${accent || "var(--clr-gold)"}">
      <div class="kpi-label">${label}</div>
      <div class="kpi-value">${value}</div>
    </div>
  `).join("");
}

// ─────────────────────────────────────────────────────────────
// Tabs
// ─────────────────────────────────────────────────────────────

function initTabs() {
  document.querySelectorAll(".tab-btn").forEach(btn => {

    btn.addEventListener("click", () => {

      document.querySelectorAll(".tab-btn")
        .forEach(b => b.classList.remove("active"));

      document.querySelectorAll(".tab-panel")
        .forEach(p => p.classList.remove("active"));

      btn.classList.add("active");

      document
        .getElementById(`tab-${btn.dataset.tab}`)
        .classList.add("active");
    });

  });
}

// ─────────────────────────────────────────────────────────────
// Genre Section
// ─────────────────────────────────────────────────────────────

async function loadGenre() {

  const res = await getGenre();

  if (!res.ok) return;

  const data = res.data;

  const labels  = data.map(d => d.genre_name);
  const revenue = data.map(d => parseFloat(d.total_revenue));
  const rentals = data.map(d => parseInt(d.total_rental));
  const pcts    = data.map(d => parseFloat(d.revenue_pct));

  // KPIs

  const totalRev  = revenue.reduce((a,b) => a+b, 0);
  const totalRent = rentals.reduce((a,b) => a+b, 0);

  buildKPIs(document.getElementById("genre-kpis"), [
    {
      label: "Genres",
      value: data.length
    },
    {
      label: "Total Rentals",
      value: totalRent.toLocaleString(),
      accent: "#B14A36"
    },
    {
      label: "Total Revenue",
      value:
        "$" +
        totalRev.toLocaleString("en-US", {
          minimumFractionDigits: 2
        }),
      accent: "#8C0902"
    },
    {
      label: "Top Genre",
      value: data[0]?.genre_name || "—",
      accent: "#FECE79"
    }
  ]);

  // Revenue Chart

  mkChart(
    "revenue_chart",
    "bar",
    labels,
    [{
      label: "Revenue ($)",
      data: revenue,
      backgroundColor: PALETTE,
      borderRadius: 6
    }],
    {
      scales: {
        y: {
          ticks: {
            callback: v => "$" + v.toLocaleString()
          },
          grid: {
            color: "rgba(0,0,0,.05)"
          }
        },
        x: {
          grid: {
            display: false
          }
        }
      }
    },
    {
      title: "Revenue by Genre",
      category: "genre",
      description: "Shows total revenue generated by each movie genre.",
      xLabel: "Genre",
      yLabel: "Revenue ($)",
      keywords: [
        "genre",
        "revenue",
        "sales",
        "earnings"
      ]
    }
  );

  // Rental Chart

  mkChart(
    "rental_chart",
    "bar",
    labels,
    [{
      label: "Rentals",
      data: rentals,
      backgroundColor: PALETTE.slice(1),
      borderRadius: 6
    }],
    {
      scales: {
        y: {
          ticks: {
            callback: v => v.toLocaleString()
          },
          grid: {
            color: "rgba(0,0,0,.05)"
          }
        },
        x: {
          grid: {
            display: false
          }
        }
      }
    },
    {
      title: "Rental Count by Genre",
      category: "genre",
      description: "Displays number of rentals completed per genre.",
      xLabel: "Genre",
      yLabel: "Rental Count",
      keywords: [
        "genre",
        "rentals",
        "frequency",
        "usage"
      ]
    }
  );

  // Share Chart

  mkChart(
    "share_chart",
    "doughnut",
    labels,
    [{
      data: pcts,
      backgroundColor: PALETTE,
      borderWidth: 2,
      borderColor: "#fff"
    }],
    {
      legend: true,
      extra: {
        plugins: {
          legend: {
            position: "right",
            labels: {
              boxWidth: 12,
              font: {
                size: 11
              }
            }
          },
          tooltip: {
            callbacks: {
              label: ctx =>
                `${ctx.label}: ${ctx.parsed.toFixed(1)}%`
            }
          }
        },
        cutout: "52%"
      }
    },
    {
      title: "Revenue Share by Genre",
      category: "genre",
      description: "Percentage contribution of each genre to total revenue.",
      xLabel: "Genre",
      yLabel: "Revenue Share %",
      keywords: [
        "genre",
        "market share",
        "distribution",
        "percentage"
      ]
    }
  );

  // Best Film Table

  const table = document.getElementById("best-film-table");

  if (table) {

    table.innerHTML = `
      <div class="section-label">Top Film per Genre</div>

      <div class="data-table-wrap">

        <table class="data-table">

          <thead>
            <tr>
              <th>Genre</th>
              <th>Best Film</th>
              <th>Revenue</th>
            </tr>
          </thead>

          <tbody>

            ${data.map(d => `
              <tr>
                <td>${d.genre_name}</td>

                <td
                  style="
                    max-width:140px;
                    overflow:hidden;
                    text-overflow:ellipsis;
                    white-space:nowrap
                  "
                >
                  ${d.best_film}
                </td>

                <td>
                  $${parseFloat(d.total_revenue).toLocaleString(
                    "en-US",
                    { minimumFractionDigits: 2 }
                  )}
                </td>
              </tr>
            `).join("")}

          </tbody>

        </table>

      </div>
    `;
  }
}

// ─────────────────────────────────────────────────────────────
// Rating Section
// ─────────────────────────────────────────────────────────────

async function loadRating() {

  const res = await getRating();

  if (!res.ok) return;

  const data = res.data;

  const labels  = data.map(d => d.rating);
  const revenue = data.map(d => parseFloat(d.total_revenue));
  const pcts    = data.map(d => parseFloat(d.rental_pct));
  const avgRent = data.map(d => parseFloat(d.avg_rental_per_film));

  const colors = labels.map(
    l => RATING_COLORS[l] || "#888"
  );

  buildKPIs(document.getElementById("rating-kpis"), [
    {
      label: "Ratings",
      value: data.length
    },
    {
      label: "Highest Revenue",
      value: data[0]?.rating || "—",
      accent: "#B14A36"
    },
    {
      label: "Revenue Leader",
      value:
        "$" +
        parseFloat(
          data[0]?.total_revenue || 0
        ).toLocaleString("en-US", {
          minimumFractionDigits: 2
        }),
      accent: "#8C0902"
    },
    {
      label: "Most Films",
      value:
        data.sort(
          (a,b) => b.num_films - a.num_films
        )[0]?.rating || "—",
      accent: "#FECE79"
    }
  ]);

  // Revenue by Rating

  mkChart(
    "rating_revenue",
    "bar",
    labels,
    [{
      label: "Revenue ($)",
      data: revenue,
      backgroundColor: colors,
      borderRadius: 6
    }],
    {},
    {
      title: "Revenue by Rating",
      category: "rating",
      description: "Revenue generated by movie rating category.",
      xLabel: "Rating",
      yLabel: "Revenue ($)",
      keywords: [
        "rating",
        "revenue",
        "movie classification"
      ]
    }
  );

  // Rental Share by Rating

  mkChart(
    "rating_share",
    "doughnut",
    labels,
    [{
      data: pcts,
      backgroundColor: colors,
      borderWidth: 2,
      borderColor: "#fff"
    }],
    {
      legend: true,
      extra: {
        cutout: "52%"
      }
    },
    {
      title: "Rental Share by Rating",
      category: "rating",
      description: "Rental distribution percentage per rating.",
      xLabel: "Rating",
      yLabel: "Rental Share %",
      keywords: [
        "rating",
        "distribution",
        "share"
      ]
    }
  );

  // Avg Rentals

  mkChart(
    "rating_rental",
    "bar",
    labels,
    [{
      label: "Avg Rentals / Film",
      data: avgRent,
      backgroundColor: colors,
      borderRadius: 6
    }],
    {},
    {
      title: "Average Rentals per Film",
      category: "rating",
      description: "Average rental frequency for films by rating.",
      xLabel: "Rating",
      yLabel: "Average Rentals",
      keywords: [
        "rating",
        "average",
        "rental frequency"
      ]
    }
  );
}

// ─────────────────────────────────────────────────────────────
// Genre × Rating
// ─────────────────────────────────────────────────────────────

async function loadGenreRating() {

  const res = await getGenreRating();

  if (!res.ok) return;

  const raw = res.data;

  const genres = [
    ...new Set(raw.map(r => r.genre_name))
  ].sort();

  const ratings = [
    "G",
    "PG",
    "PG-13",
    "R",
    "NC-17"
  ];

  const datasets = ratings.map(rating => ({
    label: rating,

    data: genres.map(genre => {

      const match = raw.find(
        r =>
          r.genre_name === genre &&
          r.rating === rating
      );

      return match
        ? parseInt(match.rental_count)
        : 0;
    }),

    backgroundColor:
      RATING_COLORS[rating] || "#888",

    borderRadius: 4
  }));

  mkChart(
    "genre_rating_chart",
    "bar",
    genres,
    datasets,
    {
      legend: true
    },
    {
      title: "Genre × Rating Distribution",
      category: "combined",
      description:
        "Rental distribution by genre and movie rating.",
      xLabel: "Genre",
      yLabel: "Rental Count",
      keywords: [
        "genre",
        "rating",
        "distribution",
        "comparison"
      ]
    }
  );
}

// ─────────────────────────────────────────────────────────────
// Rental Form
// ─────────────────────────────────────────────────────────────

async function loadRentalForm() {

  const [filmsRes, custsRes] = await Promise.all([
    getFilms(),
    getCustomers()
  ]);

  if (filmsRes.ok) {

    const sel = document.getElementById("rental-film");

    filmsRes.data.forEach(f => {

      const opt = document.createElement("option");

      opt.value = f.film_id;
      opt.textContent = `${f.title} (${f.genre})`;

      sel.appendChild(opt);

    });
  }

  if (custsRes.ok) {

    const sel = document.getElementById("rental-customer");

    custsRes.data.forEach(c => {

      const opt = document.createElement("option");

      opt.value = c.customer_id;
      opt.textContent = c.name;

      sel.appendChild(opt);

    });
  }

  document
    .getElementById("btn-add-rental")
    .addEventListener("click", async () => {

      const film_id =
        document.getElementById("rental-film").value;

      const customer_id =
        document.getElementById("rental-customer").value;

      const amount = parseFloat(
        document.getElementById("rental-amount").value
      );

      const msgEl =
        document.getElementById("rental-msg");

      msgEl.innerHTML = `
        <div class="loading-state" style="padding:.5rem">
          <div class="spinner"></div>
          Submitting…
        </div>
      `;

      try {

        const res = await postRental({
          film_id: parseInt(film_id),
          customer_id: parseInt(customer_id),
          amount
        });

        if (res.ok) {

          msgEl.innerHTML = `
            <div class="alert success">
              <div class="alert-icon">✓</div>
              <div class="alert-body">${res.message}</div>
            </div>
          `;

          setTimeout(() => {
            loadGenre();
            loadRating();
          }, 1000);

        } else {

          msgEl.innerHTML = `
            <div class="alert error">
              <div class="alert-icon">!</div>
              <div class="alert-body">${res.error}</div>
            </div>
          `;
        }

      } catch (e) {

        msgEl.innerHTML = `
          <div class="alert error">
            <div class="alert-icon">!</div>
            <div class="alert-body">${e.message}</div>
          </div>
        `;
      }

    });
}

// ─────────────────────────────────────────────────────────────
// Init
// ─────────────────────────────────────────────────────────────

export async function init() {

  initTabs();

  await Promise.all([
    loadGenre(),
    loadRating(),
    loadGenreRating(),
    loadRentalForm()
  ]);
}

export function cleanup() {}