/**
 * chart_registry.js — Central registry for all Chart.js instances.
 * Used by:
 * - AI controller
 * - AI context builder
 * - Page lifecycle cleanup
 *
 * Stores:
 * - live chart instance
 * - original chart snapshot
 * - metadata for AI semantic understanding
 */

const _registry = new Map();

/**
 * Deep clone helper
 * Prevents Chart.js mutation side-effects.
 */
function clone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

export const ChartRegistry = {

  /**
   * Register a Chart.js instance.
   *
   * @param {string} id
   * @param {Chart} chart
   * @param {Object} meta
   *
   * Example:
   * ChartRegistry.register("revenue_chart", chart, {
   *   title: "Revenue by Genre",
   *   entity: "genre",
   *   metric: "revenue",
   *   page: "movie",
   *   chartType: "bar",
   *   description: "Total revenue generated by each movie genre"
   * });
   */
  register(id, chart, meta = {}) {

    if (!id || typeof id !== "string") {
      console.warn("[ChartRegistry] Invalid chart ID:", id);
      return;
    }

    if (!chart) {
      console.warn(`[ChartRegistry] Missing chart instance for '${id}'`);
      return;
    }

    // Destroy existing chart with same ID first
    if (_registry.has(id)) {
      console.warn(`[ChartRegistry] Duplicate chart ID detected: '${id}'`);
      this.destroy(id);
    }

    const entry = {
      id,

      // Live Chart.js instance
      chart,

      // AI metadata
      meta: {
        title: meta.title || id,
        entity: meta.entity || null,
        metric: meta.metric || null,
        page: meta.page || window._currentPageKey || null,
        chartType: meta.chartType || chart.config.type,
        description: meta.description || "",
        tags: Array.isArray(meta.tags) ? meta.tags : [],
      },

      // Immutable snapshots
      originalData: clone(chart.data),
      originalOptions: clone(chart.options),

      // Registration timestamp
      createdAt: Date.now(),
    };

    _registry.set(id, entry);

    console.info(`[ChartRegistry] Registered chart: '${id}'`);
  },

  /**
   * Get registry entry by ID.
   *
   * @param {string} id
   * @returns {Object|null}
   */
  get(id) {
    return _registry.get(id) || null;
  },

  /**
   * Check if chart exists.
   *
   * @param {string} id
   * @returns {boolean}
   */
  has(id) {
    return _registry.has(id);
  },

  /**
   * Get all registered chart IDs.
   *
   * @returns {string[]}
   */
  ids() {
    return [..._registry.keys()];
  },

  /**
   * Get all registry entries.
   *
   * @returns {Array}
   */
  all() {
    return [..._registry.values()];
  },

  /**
   * Get simplified AI-friendly chart context.
   *
   * Used for:
   * - AI prompts
   * - Gemini/OpenAI context
   * - chart discovery
   */
  context() {
    return [..._registry.entries()].map(([id, entry]) => ({
      id,

      title: entry.meta.title,

      entity: entry.meta.entity,

      metric: entry.meta.metric,

      chartType: entry.chart.config.type,

      labels: entry.chart.data.labels,

      datasets: entry.chart.data.datasets.map(ds => ({
        label: ds.label || null,
      })),

      description: entry.meta.description,

      page: entry.meta.page,
    }));
  },

  /**
   * Restore chart to original state.
   *
   * @param {string} id
   */
  reset(id) {
    const entry = _registry.get(id);

    if (!entry) {
      console.warn(`[ChartRegistry] Cannot reset missing chart '${id}'`);
      return;
    }

    entry.chart.data = clone(entry.originalData);
    entry.chart.options = clone(entry.originalOptions);

    entry.chart.update();

    console.info(`[ChartRegistry] Reset chart '${id}'`);
  },

  /**
   * Destroy and remove a chart.
   *
   * @param {string} id
   */
  destroy(id) {
    const entry = _registry.get(id);

    if (!entry) return;

    try {
      entry.chart.destroy();
    } catch (e) {
      console.warn(`[ChartRegistry] Failed destroying '${id}':`, e);
    }

    _registry.delete(id);

    console.info(`[ChartRegistry] Destroyed chart '${id}'`);
  },

  /**
   * Destroy all charts.
   *
   * Called during SPA page navigation.
   */
  destroyAll() {

    for (const [id, entry] of _registry.entries()) {

      try {
        entry.chart.destroy();
      } catch (e) {
        console.warn(`[ChartRegistry] Failed destroying '${id}':`, e);
      }
    }

    _registry.clear();

    console.info("[ChartRegistry] Destroyed all charts");
  },

  /**
   * Debug helper.
   */
  debug() {
    console.table(
      [..._registry.entries()].map(([id, entry]) => ({
        id,
        type: entry.chart.config.type,
        title: entry.meta.title,
        entity: entry.meta.entity,
        metric: entry.meta.metric,
        page: entry.meta.page,
      }))
    );
  },
};